[project]
name = "practical-interview-prep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kwizera thierry", email = "thkwzr@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1",
    "django-rest-framework>=0.1.0",
    "djangorestframework>=3.18.0",
]

[project.scripts]
practical-interview-prep = "practical_interview_prep:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
